replace-karma:
	yarn remove @types/jasmine jasmine-core karma karma-chrome-launcher karma-coverage karma-jasmine karma-jasmine-html-reporter
	rm karma.conf.js src/test.ts
	yarn add -D jest jest-preset-angular @types/jest
#test